### ISSUE TITLE
"vue3-lottie": "^2.1.0",

### ISSUE THREAD

**Issue by kknono** [megasanjay/vue3-lottie#15]
hi, here has an error:
SyntaxError: Cannot use import statement outside a module

**Comment by megasanjay** [comment]
Would you mind sharing your import statement

**Comment by wflemming** [comment]
I am facing a similar issue with 2.1.0. 

`<script setup lang="ts">
import { ref } from 'vue';
import { Vue3Lottie } from 'vue3-lottie';
import 'vue3-lottie/dist/style.css';
import * as PhoneMoney from '~/assets/animations/phone-earn-money.json';
const showSignup = ref(false)
</script>`

**Comment by megasanjay** [comment]
> Cannot use import statement outside a module

Are you using this library in a project generated via Vue CLI or Vite? It should work just like any other Vue component.

**Comment by wflemming** [comment]
I am using a project with Vite, building from the following template:

https://github.com/antfu/vitesse 

Everything worked perfectly in local development but it failed to build for production. When I saw @kknono 's recent comment facing the same issue, I thought I would share.  My best guess is that it's a Vite issue.  Thanks for everything you do.

**Comment by megasanjay** [comment]
@wflemming I'll take a look at it either today or tomorrow and get you a response. Thanks for being patient. Cheers 👍🏽

**Comment by megasanjay** [comment]
@reslear Is there anything that explains this? I tried setting up the Vitesse template with the package using pnpm. That works for dev but not for the build. With yarn the dev doesn't work either. Very strange.

**Comment by reslear** [comment]
repro?

**Comment by megasanjay** [comment]
@reslear The `vitesse` folder in the packages directory. It's a very weird case, Seems to work with everything else,
