### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by Maxentr** [megasanjay/vue3-lottie#2]
Hello,
First of all, thank you for your work, finally a good library for Vue 3. Can you add support for the links (example: https://assets5.lottiefiles.com/packages/lf20_vmollwvl.json) and types for typescript. It would be perfect!

**Comment by megasanjay** [comment]
Thank you for the issue. I'll try to add link support either today or tomorrow. I was under the impression that types were already included. I'm not very familiar with TS myself. Would you be able to let me know what I should change for that?

**Comment by megasanjay** [comment]
Hi, @Maxentr I just released a new version with support for a new prop `animationLink` that you can use to provide a URL. The latest version is `1.4.0`. The docs have also been updated for this new prop: https://vue3-lottie.vercel.app/guide.html#animationlink

**Comment by Maxentr** [comment]
I just saw, thanks for being so responsive 👍. For Typescript, they have good documentation about it :
[Declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html). It is not urgent because we can declare the package ourselves but in the future, it will be good to have it.

**Comment by megasanjay** [comment]
@Maxentr Thank you for linking me to the documentation. I would very much love to learn it so I'll take a look at it and see what I can conjure up over the weekend.
