### ISSUE TITLE
ERROR  'default' is not exported

### ISSUE THREAD

**Issue by Aksoom-Hussain** [megasanjay/vue3-lottie#200]
Nuxt 3 (RC-8.0 )code did not build or generate and in development it did not loading the Lottie animations 

 

```
 ERROR  'default' is not exported by node_modules/lottie-web/build/player/lottie.js, imported by node_modules/vue3-lottie/dist/vue3-lottie.es.js                         17:33:50
file: /Users/thinkindragon/Development/TService/966rtl/apps/userRTL/node_modules/vue3-lottie/dist/vue3-lottie.es.js:2:0
1: import { defineComponent, ref, computed, watch, onMounted, openBlock, createElementBlock, normalizeStyle } from "vue";
2: import Lottie from "lottie-web";
   ^
3: var vue3Lottie_vue_vue_type_style_index_0_lang = "";
4: var _export_sfc = (sfc, props) => {
```

**Comment by megasanjay** [comment]
Instructions have been updated for Nuxt. You can find them here: https://vue3-lottie.vercel.app/guide.html#nuxt-3

**Comment by doutatsu** [comment]
I am not using Nuxt, yet this error is still present in my project:
```js
RollupError: "default" is not exported by "node_modules/.pnpm/lottie-web@5.10.2/node_modules/lottie-web/build/player/lottie.js", imported by "node_modules/.pnpm/vue3-lottie@2.5.0_vue@3.2.47/node_modules/vue3-lottie/dist/vue3-lottie.es.js".
10:58:54.318

<br class="Apple-interchange-newline">
```

I am using Vite + Vue

**Comment by handanyolak** [comment]
Same issue here. I'm using Nuxt 3 along with Vite. I have followed the installation guide for Nuxt 3 provided by the plugin's documentation.

**Comment by Aksoom-Hussain** [comment]
> Same issue here. I'm using Nuxt 3 along with Vite. I have followed the installation guide for Nuxt 3 provided by the plugin's documentation.

the issue is already resolved 
make sure you follow the instruction [](https://vue3-lottie.vercel.app/introduction/nuxt-3)
and keep the component in <client-only> tag
