### ISSUE TITLE
rendererSettings prop not working

### ISSUE THREAD

**Issue by marcorodriguesdev** [megasanjay/vue3-lottie#255]
Hi. 

When defining the renderSettings prop object with some values, the dom renders "renderersettings="[object Object]"

Component code:
`<Vue3Lottie
        :animationData="Preloader"
        :loop="true"
        :rendererSettings="{
          preserveAspectRatio: 'xMinYMin slice'
        }"
      />`

**Comment by megasanjay** [comment]
Hi, @marcorodriguesdev I seem to have missed that prop. I'll add it and push a patch version up to npm. I'll ping you when it's done

**Comment by megasanjay** [comment]
@marcorodriguesdev Just pushed an update for this issue. Try updating your package version and it should be supported now :)
