### ISSUE TITLE
layers是空 一直报错 无法使用该组件

### ISSUE THREAD

**Issue by HUIDIZ** [megasanjay/vue3-lottie#257]
![image](https://user-images.githubusercontent.com/24472084/197723563-4c984988-c685-413c-8daf-5a2ac45472fa.png)
![image](https://user-images.githubusercontent.com/24472084/197723317-706f7c3c-069e-4f7b-8daa-5e3496cf2a2d.png)
使用版本：最新
vue3

**Comment by marcus-universe** [comment]
I have something similar since the new update 2.3.1
![image](https://user-images.githubusercontent.com/26997041/197753405-fb5186ae-be8f-4264-b04f-4940775f822d.png)

**Comment by megasanjay** [comment]
Just pushed a bunch of changes to my object type checking. Use `npm install vue3-lottie@latest --save` or `yarn add vue3-lottie@latest` to get the latest version

**Comment by megasanjay** [comment]
@HUIDIZ @marcus-universe Thank you for providing feedback btw ❤️
