### ISSUE TITLE
Can't get length of undefined on 2.3.1

### ISSUE THREAD

**Issue by dkbay** [megasanjay/vue3-lottie#258]
It seems changing this `JSON.parse(JSON.stringify(` to `clonedeep` has caused some issues in 2.3.1 that aren't present in 2.3.0 which causes anything you put into the `animation-data` prop to not work.

Animation-link still works.
Reverting to 2.3.1 also works.

Seems to stem from this commit: https://github.com/megasanjay/vue3-lottie/commit/ea164bc3dffaec3032970f25fcbe012bc3fc146b

**Comment by megasanjay** [comment]
Hi @dkbay. I'm super sorry for the trouble caused. I just reverted the change and pushed a new version to npm. https://www.npmjs.com/package/vue3-lottie/v/2.3.2
