### ISSUE TITLE
renderer param

### ISSUE THREAD

**Issue by joostvc** [megasanjay/vue3-lottie#264]
Hi, is it posible to make the renderer `svg|canvas` param configurable like all other params? 

So you can do this: `<Vue3Lottie :animationData="AstronautJSON" :height="200" :width="200" :renderer="canvas" />`

**Comment by megasanjay** [comment]
This was just added to v2.4.0 for you. The default is `svg` but you can also use `canvas` or `html` if you like. Use `npm install vue3-lottie@latest --save` or `yarn add vue3-lottie@latest` to get the latest version.

**Comment by megasanjay** [comment]
@joostvc Let me know if this works for you :)
