### ISSUE TITLE
Сan't set the correct animation size

### ISSUE THREAD

**Issue by pefka** [megasanjay/vue3-lottie#273]
hi,
this code:
```
    <LottieAnimation
    animationLink="/images/150-refresh-change-outline-edited.json"
    :height="40"
    :width="40"
  />
```
generates this svg after vue serve:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500" width="500" height="500" style="width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px);" preserveAspectRatio="xMidYMid meet">`

**"width="500" height="500""**

Therefore, I get a huge 500x500 frame on the page and a small 40x40 icon in it. How can I fix this? I want to set dimensions like 40 by 40 and not set any extra dimensions for the viewbox

**Comment by megasanjay** [comment]
@pefka Your animationLink prop needs to be a url. Also try using `height="40px"`

**Comment by pefka** [comment]
@megasanjay thank for reply,


I tried 40px, same effect

It turns out that styles are added, but they are added with prefixes that my browser does not understand, like this:
`element {
  --lottie-animation-container-width: 40px;
  --lottie-animation-container-height: 40px;
  --lottie-animation-container-background-color: transparent;
}`

<img width="989" alt="Screenshot 2022-11-24 at 6 42 55 PM" src="https://user-images.githubusercontent.com/77622394/203842275-e0066027-16de-4e26-809a-1fe7291144a7.png">

<img width="749" alt="Screenshot 2022-11-24 at 6 43 02 PM" src="https://user-images.githubusercontent.com/77622394/203842312-db612e8f-374c-4207-947d-ac35ae1da516.png">

**Comment by megasanjay** [comment]
That is correct. Those are css variables that are added inline. The actual width and height of the container is in the child element.
