### ISSUE TITLE
Hight and With not taking affect.

### ISSUE THREAD

**Issue by mallle** [megasanjay/vue3-lottie#287]
I'm using:
"vue3-lottie": "^2.4.0"
"nuxt": "3.1.0",

And implemented the vue3-lottie as stated in the documentation:
But the height and the with are not taking any effect. 

<img width="947" alt="Screenshot 2023-01-26 at 11 51 36" src="https://user-images.githubusercontent.com/25229717/214818172-938d8eed-eeed-4e42-ba34-914ab791bcb4.png">

<img width="961" alt="Screenshot 2023-01-26 at 11 52 20" src="https://user-images.githubusercontent.com/25229717/214818318-651d6e2e-55f8-4780-be00-a3fb79f2617c.png">

```
<Vue3Lottie
    animation-link="https://assets10.lottiefiles.com/packages/lf20_soCRuE.json"
    :height="200"
    :width="200"
/>
```

Does anyone know what I'm doing wrong here?

**Comment by megasanjay** [comment]
Would you mind adding a reproduction on [codesandbox.io](https://codesandbox.io/)?
