### ISSUE TITLE
Component resolving as custom element on dev using Nuxt 3 TypeScript

### ISSUE THREAD

**Issue by kuroji-fusky** [megasanjay/vue3-lottie#292]
I've followed the exact steps for Nuxt `^3.1.0` using TypeScript; and it doesn't display anything, upon inspecting from DevTools, the component is shown literally as a `<vue3lottie />` tag in HTML. Both running the dev and build commands run the same issue

![image](https://user-images.githubusercontent.com/94678583/217430071-d7795cd0-1b8d-4a55-a859-1b9fdb054e1e.png)
![image](https://user-images.githubusercontent.com/94678583/217427921-ba3dc574-d438-4241-b547-cbfc2aa19569.png)

I'm aware that the package is still experimental though I'm exactly unsure if I tripped something during installation, or if I messed something up along the way.

- [CodeSandbox Reproduction](https://codesandbox.io/p/sandbox/bold-driscoll-1wdnse?file=%2Fapp.vue)

**Comment by kuroji-fusky** [comment]
Oh my bad! It was on me, I made a typo!

**Comment by deevanych** [comment]
> Oh my bad! It was on me, I made a typo!

Hi! Can you share a issue resolve? I have same error, but I can't see the typo - i made steps from install guide, but is not working (

**Comment by megasanjay** [comment]
> > Oh my bad! It was on me, I made a typo!
> 
> Hi! Can you share a issue resolve? I have same error, but I can't see the typo - i made steps from install guide, but is not working (

Do you have a repository on github?

**Comment by deevanych** [comment]
> > > Oh my bad! It was on me, I made a typo!
> > 
> > 
> > Hi! Can you share a issue resolve? I have same error, but I can't see the typo - i made steps from install guide, but is not working (
> 
> Do you have a repository on github?

nope, but I can share screenshot - i just made all steps from installation guide

![image](https://github.com/megasanjay/vue3-lottie/assets/4135982/8ac6833a-7f38-4be5-87fb-a8378c854492)

**Comment by megasanjay** [comment]
1. Verify that you are on version 3 of the library just in case.
2. Try `nuxtApp.vueApp.use(Vue3Lottie, { name: 'Vue3Lottie' })`

**Comment by deevanych** [comment]
> 1. Verify that you are on version 3 of the library just in case.
> 2. Try `nuxtApp.vueApp.use(Vue3Lottie, { name: 'Vue3Lottie' })`

1. 3.0.0
2. I have tried earlier, but nothing is happened.
![image](https://github.com/megasanjay/vue3-lottie/assets/4135982/a5b98a50-2505-4f81-b1be-322c4c4f2420)

**Comment by megasanjay** [comment]
This might be easier if you post a reproduction repository on GitHub. I'm not immediately seeing what the issue is :(

**Comment by deevanych** [comment]
> This might be easier if you post a reproduction repository on GitHub. I'm not immediately seeing what the issue is :(

uh, don't care, I'll find another plugin for Lottie or will use native js Lottie. thx for help, cya!

p.s. u have a nice profile. cool!

**Comment by megasanjay** [comment]
Good luck :)
