### ISSUE TITLE
Option to use "lighter" lottie builds

### ISSUE THREAD

**Issue by trueter** [megasanjay/vue3-lottie#294]
vue3-lottie is by far the biggest chunk in my bundle. lottie-web actually exposes different builds, e.g. only including the svg renderer and it would be great if as a vue3-lottie user I would be able to control with of those builds is loaded.

On another note, the es build does not seem to properly treeshake lodash, causing a large bundle size of vue3-lottie itself.

**Comment by tafelnl** [comment]
My PR #296 partially solves this. It makes use of the proper lodash package to enable tree-shaking. I don't know much about the `lottie-web` stuff though. Haven't looked into that.

(I am _not_ one of the maintainers by the way)

**Comment by tafelnl** [comment]
Related: https://github.com/airbnb/lottie-web/issues/1184

**Comment by megasanjay** [comment]
Thank you for the PR. Let me see if I can release a new version for it

**Comment by megasanjay** [comment]
Thanks, @tafelnl for your work. I just released v2.5. Should be available for download here: https://www.npmjs.com/package/vue3-lottie/v/2.5.0

**Comment by megasanjay** [comment]
This doesn't solve the original issue of adding user-selectable bundles but I can look at it in the future. Closing this issue for now
