### ISSUE TITLE
lottieAnimation.goToAndStop is not a function

### ISSUE THREAD

**Issue by 54mu3l** [megasanjay/vue3-lottie#30]
I'm trying to call `this.$refs.anim.goToAndStop(18);` within `mounted`. And I get this error:
`lottieAnimation.goToAndStop is not a function`

I created the following Sandbox to reproduce this behavior: https://codesandbox.io/s/sparkling-snow-7rr64w?file=/src/pages/Index.vue

**Comment by megasanjay** [comment]
Will take a look at this over the weekend.

**Comment by 54mu3l** [comment]
> The new version is v2.2.0. Let me know if it works for you :)

Works flawlessly. Thank you!

**Comment by megasanjay** [comment]
@54mu3l There was also a bug with the `autoPlay` prop that was fixed. The latest version is [2.2.4](https://www.npmjs.com/package/vue3-lottie). Thank you for using this library 😄

**Comment by 54mu3l** [comment]
Thank you for your work!
