### ISSUE TITLE
How to observe the mouseout event

### ISSUE THREAD

**Issue by lzz29** [megasanjay/vue3-lottie#305]
Hello
My animation is loop state.
When I mouse levae, I want to return to the original state. 
I don't  find events or methods to return.
If I add mouseout event, it's always trigger.
Is there any other way？

**Comment by megasanjay** [comment]
What do you mean by original state? There is a [pause](https://vue3-lottie.vercel.app/guide.html#pause) method if you want to control playback manually. Or stop if you want to reset back to the start.
