### ISSUE TITLE
Invalid HTML on `image`

### ISSUE THREAD

**Issue by Vannsl** [megasanjay/vue3-lottie#315]
When running the HTML rendered by the `vue3-lottie` component, W3C shows the following errors:

```
Error: Element image is missing required attribute height.
Error: Element image is missing required attribute width.
```

on the first `<image>` tag within the HTML_

```
<div data-id="6hgoyK4maBR4WOsJGNLF" class="lottie-animation-container" aria-hidden="true" style="--lottie-animation-container-width: 20px; --lottie-animation-container-height: 20px; --lottie-animation-container-background-color: transparent;"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 277 272" width="277" height="272" preserveAspectRatio="xMidYMid meet" style="width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;"><defs><clipPath id="__lottie_element_2"><rect width="277" height="272" x="0" y="0"></rect></clipPath><image xlink:href="data:image/png;base64, ...
```

🚨 I'm not sure if this is a problem with this library, or rather the Lottie JSON. I'm sorry, if it is rather the JSON or another lib!

<img width="1317" alt="Screenshot 2023-05-16 at 16 18 48" src="https://github.com/megasanjay/vue3-lottie/assets/5849721/a78a3b18-02c6-4526-b96a-b301e6b8b229">

**Comment by megasanjay** [comment]
This is something that the `lottie-web` library generates. I can take a look and see if this is a more significant concern and have the tags be generated after generation but since it's inside a SVG I'm not very hopeful about this promise. Do other svg usually have this as default?

**Comment by Vannsl** [comment]
I rarely see `svg`'s using the `<image>` tag. Unfortunately I cannot answer this. I'd assume so, at least if they want to have valid HTML. MDN confirms that `width` and `height` are required attributes: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image#specific_attributes

**Comment by megasanjay** [comment]
Did some more checking. This is definitely coming from inside the Lottie file itself. This [example](https://vue3-lottie.vercel.app/examples.html#using-a-custom-assets-path) has the same issue since it uses a custom external asset. 

I'm sorry but this will have to be fixed at the [`lottie-web](https://github.com/airbnb/lottie-web)` level since that is what I use for the rendering of the animation.

**Comment by Vannsl** [comment]
Thank you for the help! I'll move this to `lottie-web`instead!
