### ISSUE TITLE
No declaration file in Vue3

### ISSUE THREAD

**Issue by Sukaato** [megasanjay/vue3-lottie#338]
**Describe the bug**
No declaration module found.

**To Reproduce**
1. Create a new vue project with Vite (vue + ts)
2. Install `vue3-lottie`
3. Add `import Vue3Lottie from 'vue3-lottie';` in main.ts
4. See build error

**Expected behavior**
No build error

**Screenshots**
![image](https://github.com/megasanjay/vue3-lottie/assets/44368476/8c9a6be4-781a-4fbe-b24d-c85092103ae7)

**Additional context**
dependencies
```
    "@vueuse/core": "^10.1.2",
    "lucide-vue-next": "^0.233.0",
    "vue": "^3.2.47",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.2.2",
    "vue3-lottie": "^2.7.3"
```
devDependencies
```
    "@tailwindcss/typography": "^0.5.9",
    "@types/node": "^18.16.18",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/eslint-config-typescript": "^11.0.3",
    "audit-ci": "^6.6.1",
    "autoprefixer": "^10.4.14",
    "daisyui": "^3.1.1",
    "eslint": "^8.43.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^9.14.1",
    "postcss": "^8.4.24",
    "prettier": "^2.8.8",
    "sass": "^1.63.4",
    "tailwind-scrollbar": "^3.0.4",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.1.3",
    "vite": "^4.3.9",
    "vue-eslint-parser": "^9.3.1",
    "vue-tsc": "^1.8.0"
```

**Comment by megasanjay** [comment]
Running the package on a new project works correctly on my end: 

![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/0f87853c-7b6c-4b59-b93c-c0cb389afd78)

![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/2115ba82-3f24-4521-91e8-9a68c60221d2)

**Comment by megasanjay** [comment]
Can you check your `package-lock.json` file to see which version of the `vue3-lottie` package was installed on your system?

**Comment by Sukaato** [comment]
I still get the error after deleting the `node cache`, deleting the `package-lock.json`, deleting the `node_module `and reinstalling my project.

And `vue3-lottie` still in version `2.7.3` with the same error

**Comment by megasanjay** [comment]
Do you have Volar installed on your VSCode?

**Comment by MarcusAngel** [comment]
Missing type declarations has nothing to do with the volar extension. There is physically no type declarations in the package

**Comment by megasanjay** [comment]
I've updated the build process and added the additional files to the package. @Sukaato, can you install `v2.7.5-beta.2` and see if that works for you?

```bash
yarn add vue3-lottie@2.7.5-beta.2
```

It works for me in a new vue project.

**Comment by megasanjay** [comment]
@Sukaato RePing to see if the beta package worked for you. 

@MarcusAngel Did you have the same issue in any of your projects?

**Comment by megasanjay** [comment]
Awesome. Thank you for responding. I'll release a new version on the main branch with the fixes.

**Comment by MarcusAngel** [comment]
Thanks! Will update as son as the new release is live

**Comment by megasanjay** [comment]
Thank you, everyone, for your patience. [V3](https://www.npmjs.com/package/vue3-lottie/v/3.0.0) is now available for download.

I decided to mark this version as a breaking change. I figured this was the best way since apps may break with the lack of the old CSS file.
