### ISSUE TITLE
 ERROR  Missing "./dist/style.css" specifier in "vue3-lottie" package  - Nuxt 3 

### ISSUE THREAD

**Issue by MarcusAngel** [megasanjay/vue3-lottie#355]
Getting the following error when running the dev server or building a nuxt 3 app

```
ERROR  Missing "./dist/style.css" specifier in "vue3-lottie" package
``` 
 This is completely blocking as it prevent building outright

**Comment by megasanjay** [comment]
If you are on v3 of the package you can remove that import line. 

https://vue3-lottie.vercel.app/introduction/v3

**Comment by MarcusAngel** [comment]
Yes apologies, I did't remove it from all locations! Thanks!
