### ISSUE TITLE
How to check if the animation is playing

### ISSUE THREAD

**Issue by Matoseb** [megasanjay/vue3-lottie#373]
It seems there is no way to check the lottieAnimation isPlaying property.

Maybe we should have access to the lottieAnimation private variable?

**Comment by megasanjay** [comment]
In what context would you need to access the playing state? If you want manual control there is an example with refs you can use: https://vue3-lottie.vercel.app/examples#using-reactive-props-to-control-the-animation

**Comment by Matoseb** [comment]
Unfortunately it's a mix of custom interaction I'm doing. It has to play once on hover.
For now, I'm managing a custom Boolean `isPlaying` based on the event `onComplete`.
