### ISSUE TITLE
dotlottie files

### ISSUE THREAD

**Issue by bluelemonade** [megasanjay/vue3-lottie#386]
Hi, is it possible to play dotlottie compressed files?

regards

**Comment by megasanjay** [comment]
Currently, this is not possible due to `lottie-web` not supporting dot lotties. However, I am looking into it to see if I can integrate a dot lottie player into this component. 

I must warn you that this could take a while though.

**Comment by bluelemonade** [comment]
hi, thanks, I go with the light player, works great.
