### ISSUE TITLE
Eval Issue

### ISSUE THREAD

**Issue by Awais-019** [megasanjay/vue3-lottie#399]
### How can I get rid of this errror

transforming (1003) node_modules/date-fns/esm/parse/_lib/parsers/EraParser.jsnode_modules/vue3-lottie/node_modules/lottie-web/build/player/lottie.js (17010:32) Use of eval in "node_modules/vue3-lottie/node_modules/lottie-web/build/player/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.

**Comment by megasanjay** [comment]
This is an issue with the upstream [airbnb/lottie-web](https://github.com/airbnb/lottie-web) library. There is nothing I can do about this for the moment. It needs to be fixed by them

**Comment by mydansun** [comment]
For anyone using vite, you may define an alias:

```js
alias: {
"lottie-web": path.resolve(__dirname, "node_modules/lottie-web/build/player/lottie_light.js")
}
```
