### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ArgekarStudios** [megasanjay/vue3-lottie#4]
need typescript support

**Comment by megasanjay** [comment]
Can you try `version 1.4.1-beta` and see if it fixes your issue?

**Comment by megasanjay** [comment]
@reslear Thank you for that. I think I have an understanding of it now. Let me see if I can release a new version

**Comment by reslear** [comment]
see example  https://github.com/Akryum/vue-mention/tree/next/packages/vue-mention

and need exclude lottie-web from bundle 500kb is big )

**Comment by reslear** [comment]
and remove `vue-class-component`

**Comment by megasanjay** [comment]
Thank you for the example. I'll take a look at it. In the meantime could you try `1.4.3-beta`

**Comment by reslear** [comment]
@megasanjay no, same

**Comment by reslear** [comment]
@megasanjay I can do this, need help?

**Comment by megasanjay** [comment]
Yes, please. I seem to be missing something. Thank you

**Comment by megasanjay** [comment]
I don't think the pr branch was functional so I reverted to the original for now. I'll keep looking into it in the meantime.

**Comment by reslear** [comment]
hi @megasanjay done) see please #9 or test [npmjs.com/package/@reslear/vue3-lottie](https://www.npmjs.com/package/@reslear/vue3-lottie)

**Comment by megasanjay** [comment]
@reslear You have done so much work. let me merge everything and publish it

**Comment by megasanjay** [comment]
Closing this issue thanks to @reslear hard work. The new version number is `v2.0.2`
