### ISSUE TITLE
change animationdata dynamically

### ISSUE THREAD

**Issue by Shahryar1991** [megasanjay/vue3-lottie#404]
Is there any way to dynamically change the animation data?

**Comment by wellington-tinho** [comment]
In my case I managed to solve by putting a "watch" for each time the link is changed, generate a new id for the parent component and, in this way, re-render the whole element.

**Comment by megasanjay** [comment]
This is now natively possible in v3.2.0. You can pass a dynamic prop and the animation container should be updated
