### ISSUE TITLE
component type support

### ISSUE THREAD

**Issue by lctech-bill** [megasanjay/vue3-lottie#415]
Hi, I follow the document to use `<Vue3Lottie>` at `Nuxt3`

https://vue3-lottie.vercel.app/introduction/nuxt-3

everything is fine, but...
I hope I can `go defintion` of `<Vue3Lottie>` at `<template>`

how to `declare` type of `<Vue3Lottie>` globally at `nuxt3` ?
I don't want `import { Vue3Lottie } from 'vue3-lottie'` in everywhere

thank you

**Comment by megasanjay** [comment]
If you create a plugin, Vue3Lottie will available globaly
