### ISSUE TITLE
couldn't load dotlottie files with animationLink

### ISSUE THREAD

**Issue by shpkng** [megasanjay/vue3-lottie#421]
Hi, 

I am seeking for Vue3 plugin for dotLottie and found this project. 

According to descriptions on npmjs.com, this plugin should work with dotLottie files. 

However when I write codes like:

![image](https://github.com/megasanjay/vue3-lottie/assets/7542219/4f6bd41e-fcfb-40ed-b5bd-30fb1c0b617d)

There is an error:

![image](https://github.com/megasanjay/vue3-lottie/assets/7542219/33e5e127-4c0d-4847-b0ab-34ab5f3c84ba)

Am I doing something wrong?

**Comment by megasanjay** [comment]
This package doesn't support dotLottie files. Not sure where in the description is says that. 

If you need a dotLottie player, refer to this: #386
