### ISSUE TITLE
How to get current duration in onEnterFrame callback?

### ISSUE THREAD

**Issue by illuz** [megasanjay/vue3-lottie#450]
- In `onEnterFrame` callback, I want to get current frame index but it's first argument is undefined.
- `getDuration` get total duration not current.

It's there a way to get current frame index from Vue3Lottie instance?

**Comment by acabreragnz** [comment]
Hi @megasanjay,

Is there any update on this issue?

In the meantime, I worked around it by patching the package and using the following implementation in my app:

### Patch in the library

![image](https://github.com/user-attachments/assets/2d0618bd-0e3e-48f1-a7b9-c9921bb71238)

### My component
```vue
<script lang="ts" setup>
import { AnimationItem, BMEnterFrameEvent } from 'lottie-web';

function initializeAnimationInstance(lottieAnimation: AnimationItem): void {
  lottieAnimation.addEventListener('enterFrame', onEnterFrame);
}

function onEnterFrame(enterFrameEvent: BMEnterFrameEvent): void {
  console.log('Current frame:', enterFrameEvent.currentTime);
}
</script>

<template>
  <Vue3Lottie
    @on-animation-loaded="initializeAnimationInstance"
  />
</template>
```


This approach works well for my use case, but I'd appreciate any updates or thoughts on a more official fix.

Thanks!
