### ISSUE TITLE
lottie won't render in Suspense!

### ISSUE THREAD

**Issue by Shahryar1991** [megasanjay/vue3-lottie#502]
I've created a component that has your component in it and used my component in a page that has Suspense template.

now lottie is not rendered!

I didn't have this problem in version 2.7.4.

**Comment by megasanjay** [comment]
Could you provide an example on codesandbox or stackblitz?

**Comment by megasanjay** [comment]
Interesting. I think this is due to the fact that I don't watch for animationData changes. I think I know how this should be fixed. Let me try that and see if it works. Thank you for the reproduction

**Comment by megasanjay** [comment]
Fixed with v3.3
