### ISSUE TITLE
Nuxt 3 - SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by jofftiquez** [megasanjay/vue3-lottie#514]
**Plugin**

```js
import { defineNuxtPlugin } from '#imports';
import { Vue3Lottie } from 'vue3-lottie';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('Vue3Lottie', Vue3Lottie);
});
```

**Component**

```html

<script setup>
import { Vue3Lottie } from 'vue3-lottie';
</script>

<template>
  <div class="flex flex-col items-center justify-center h-screen">
    <client-only>
      <Vue3Lottie
        animationLink="@/assets/animations/splashscreen.json"
        :height="200"
        :width="200"
      />
    </client-only>
  </div>
</template>
```

**Error**

> SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Additional information**

Take note that I am trying to load a local json asset. I can confirm that the json file is working properly in lottie viewer online. However trying absolute path and relative path still results to the same error.

**Comment by megasanjay** [comment]
I would try loading the json file into a ref variable inside your script tag. Also you should use `animationData` in this instance. `animationLink` is for remote URLs
