### ISSUE TITLE
Failed to resolve component

### ISSUE THREAD

**Issue by artrayd** [megasanjay/vue3-lottie#523]
Failed to resolve component: Vue3Lottie
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

Not working in Nuxt3, done according to provided guidelines

```
import { Vue3Lottie } from 'vue3-lottie'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component(Vue3Lottie, { name: 'Vue3Lottie' })
})

``` 

Nuxt: 3.9.3

**Comment by artrayd** [comment]
Regular import works well 
```
<template>
    <client-only>
      <Vue3Lottie :animationData="animationData" :height="200" :width="200" />
    </client-only>
</template>

<script setup lang="ts">
import { Vue3Lottie } from 'vue3-lottie'
</script>
```

**Comment by megasanjay** [comment]
Thank you @Mini-ghost, i'll make those changes in the docs

**Comment by kratos-digital** [comment]
This solution from @Mini-ghost returns same error for me, and when using import it works using animationLink, but not working when using json file.
