### ISSUE TITLE
How to remove "transform: translate3d(0px, 0px, 0px);" from style?

### ISSUE THREAD

**Issue by kennomena** [megasanjay/vue3-lottie#528]
I have a issue where google chrome render this lottie and it is blurry
![image](https://github.com/megasanjay/vue3-lottie/assets/99307151/9b0322d5-0458-4311-9118-5817535a71bd)

I saw a code and suddenly noticed translate3d in style
![image](https://github.com/megasanjay/vue3-lottie/assets/99307151/1dd8d0b1-926b-45dc-9444-ac54434b4109)

This is after I remove a code, it is not blur anymore
![image](https://github.com/megasanjay/vue3-lottie/assets/99307151/62e7e119-79e2-45c2-b5a3-55dc4b2fe2f3)

My project is nuxt 3

![image](https://github.com/megasanjay/vue3-lottie/assets/99307151/e153aa21-eaee-48ae-a11d-3562dd605523)

**Comment by kennomena** [comment]
I added this and it fixed somehow
`:renderer-settings="{ viewBoxOnly: true }`

**Comment by megasanjay** [comment]
That's strange. I have that translate for scaling svgs. I can take a look and see why that affected you: https://github.com/megasanjay/vue3-lottie/blob/main/packages/vue3-lottie/src/vue3-lottie.vue#L198-L208
