### ISSUE TITLE
Lottie player is huge and causing a massive drop in LightHouse performance scores. Can the script be lazy loaded?

### ISSUE THREAD

**Issue by toddpadwick** [megasanjay/vue3-lottie#529]
![Screenshot 2024-03-12 at 11 09 41](https://github.com/megasanjay/vue3-lottie/assets/36191462/5a1156de-7d95-486e-8984-0d1adbe5bf57)

Looking at this analysis display of my client side bundles, lottie player is the biggest payload. Is there a way to lazy load the vue3 lottie resources in some way?

**Comment by wizzer711** [comment]
Also seeing exactly the same issue.

**Comment by toddpadwick** [comment]
@wizzer711  I am currently working with our motion graphics guy to try this alternative solution – looks like it might be far superior in interactivity and performance. https://rive.app/blog/rive-as-a-lottie-alternative

**Comment by wizzer711** [comment]
@toddpadwick ah interesting not came across that one before, I'll take a look thank you!

**Comment by megasanjay** [comment]
I think rive is a good alternative to Lotties (especially if you need reactivity). Unfortunately, in this library the core `lottie-web` is the largest dependency and there isn't really a better alternative. I think a dotlottie player might also work for you but those, currently, don't have the full interactivity suite. 

A v3,3 version of `vue3-lottie` library was released with some performance improvements. You can try and see if that makes your performance better. 

PS: @toddpadwick What is the tool you are using for screenshot of the package analysis on nuxt?

**Comment by toddpadwick** [comment]
Thanks @megasanjay . If you have the Nuxt CLI installed, you can simply run `nuxi analyze` (or in my case `npx nuxi analyze`) - a nice little out-of-the-box tool :) 
https://nuxt.com/docs/api/commands/analyze

**Comment by megasanjay** [comment]
Thank you for the Nuxt info. I just ran it on my own Nuxt project and it had the same result. Until a lottie -> rive converter exists, the sheer number of free lotties you can use will keep it popular for the time being.

If I get some time, I will explore a rive vue component that is similar to the lottie one.
