### ISSUE TITLE
 The bug that excessively occupies system memory seems to indicate a memory leak issue.

### ISSUE THREAD

**Issue by kustone** [megasanjay/vue3-lottie#531]
In the Windows/Nuxt3 v11 environment, I found that the vue3-lottie component renders using SVG, and when I enable autoplay and infinite looping, the memory usage within the tab spikes to 500-2000MB, significantly occupying system memory. This seems to indicate a memory leak issue. When I stop using the vue3-lottie component, the memory usage returns to normal. This problem was not present when using the Vue2 version previously.

**Comment by kustone** [comment]
I seem to have found the root cause of the problem, which lies in the code of the lottie-web package. When using both the vue3-lottie and lottie-web libraries with SVG rendering and enabling loop looping and autoplay, the browser tab consumes around 200MB of system memory after page load, gradually increasing to 500-900MB or higher within 10 seconds. Sometimes, the browser's memory recycling mechanism doesn't work effectively, and even when it does, it only maintains around 400MB, or repeated refreshes cause memory overflow, leading to page lagging or crashing.
﻿
However, when I use the script tag to import lottie-player.js, under the same conditions mentioned above, the memory stays at around 150-200MB after page load. Then, after the browser's memory recycling mechanism triggers, it stays around 73MB, and the aforementioned bug does not occur. Below is my solution, hoping it can help everyone avoid wasting a lot of time and effort on this issue!
﻿
My project: NUXT (v3.11) + Vue3 + ArcoDesign
System environment: Windows 11, EDGE/Chrome browsers
Solution:
﻿
Stop using vue3-lottie and lottie-web (because they currently have bugs).
Online import or download and locally import: https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js
You can refer to my Nuxt component below, hoping it can help you!

``` Vue
<template>
  <div>
    <lottie-player ref="lottie" src="/image/lottie/4MMSzbLIE3.json" background="transparent" speed="2"
          style="width: 300px; height: 300px" direction="1" mode="normal" loop autoplay></lottie-player>
    <a-space>
      <a-button type="primary" @click="lottie.play()">播放</a-button>
      <a-button type="primary" @click="lottie.stop()">停止</a-button>
    </a-space>
  </div>
</template>

<script setup>
import "assets/js/lottie-player.js";
const lottie = ref(null);
const stop = () => {
  lottie.value.stop();
};
</script>

<style lang="less"></style>

```
![QQ截图20240324190737](https://github.com/megasanjay/vue3-lottie/assets/43320790/94a314ab-9672-48ae-b42a-5f85f52f6de8)
![D124D95415C116B45DC749849E1455C2](https://github.com/megasanjay/vue3-lottie/assets/43320790/e2bc1140-e73d-4f2d-bab8-e6e785d95bfe)

**Comment by megasanjay** [comment]
Thanks for bringing this up. I would suggest using the browser management tool to see if you see the same results.
Just trying it on pages that have with infinite lotties showing and against the Nuxt.com homepage I see the same numbers: 

![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/673bbe55-3b12-462f-8cdf-3b398d73d93c)

**Comment by megasanjay** [comment]
It's my 404 page that has a lottie on it that I'm using to check. Actually it runs lower 
![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/a8bbbf75-4255-476c-9189-a0acdca5bbc6)

**Comment by megasanjay** [comment]
@kustone Please let me know with your results

**Comment by megasanjay** [comment]
My examples page has a much higher footprint but this can be attributed to over 10 lotties being rendered all at once with varying levels on interaction on them: 
![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/0a890ca7-adb4-4d45-93d5-b86ae38e86d2)

**Comment by megasanjay** [comment]
For the task manager results: 

Only this github issue page opened.
![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/56c08971-5543-4dd3-ac9f-07879f81e536)

This github issue page + nuxt homepage
![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/c6fc8458-e554-4b64-89a4-266e32d9509c)

This github issue page + a page with a lottie opened.
![image](https://github.com/megasanjay/vue3-lottie/assets/21206996/e75f64cb-3bf2-4c08-8f42-0ab096035123)

I'm not seeing giant swings like you here

**Comment by alessiochiffi** [comment]
I've also experienced the same issue with vue3-lottie on nuxt 3, with chrome crashing the page due to a memory leak.

**Comment by megasanjay** [comment]
@alessiochiffi Do you have a copy of the website/lottie for this. Would be something worth looking into

**Comment by alessiochiffi** [comment]
Unfortunately it's a private repo and we ended up removing the Lottie implementation from the site due to this issue. I will try to replicate and share it here as soon as I can

**Comment by Ischafak** [comment]
same results for me. it really has memory bugs. i see ton of lottie things
