### ISSUE TITLE
Images not loading when included in JSON

### ISSUE THREAD

**Issue by rttmax** [megasanjay/vue3-lottie#532]
Images embedded directly in the json can not not loaded (404).

i.e.:

```    
"assets": [
        {
            "id": "image_0",
            "w": 34,
            "h": 19,
            "u": "/images/",
            "p": "data:image/png;base64,iVBORw0KGgoAAAANgg==",
            "e": 0
        },
        ...
```

The image path ("/images/") is appended in front of the URL. URLs then look like this:

/images/data:image/png;base64,iVBORw...

When in manually set "u" to "" everything works as expected.

**Comment by megasanjay** [comment]
Are you using assets path: https://vue3-lottie.vercel.app/api/props#assetspath
