### ISSUE TITLE
any idea to reduce the bundle size?

### ISSUE THREAD

**Issue by mzy2240** [megasanjay/vue3-lottie#54]
great work! I just wonder whether you have any idea on reducing the bundle size or providing a CDN link? Currently the bundled lottie.js  is huge and it is literally the largest module in my project (rendered size > 500kb).

**Comment by megasanjay** [comment]
Hi @mzy2240 Unfortunately the large bundle size is due to the [`lottie-web`](https://github.com/airbnb/lottie-web) library. I have some ideas planned for some bundle size reduction but it might take me some time to get on it. I will let you know if it pans out.
