### ISSUE TITLE
AnimationData needs to update dynamically.

### ISSUE THREAD

**Issue by sanjaykumar66** [megasanjay/vue3-lottie#60]
I'm trying to update Animation Data but it not working properly. unless before updating remove the component and re-render it. Is there any other workaround for this?

**Comment by megasanjay** [comment]
This is intentional. Having the animation data update dynamically was causing a lot of issues with the event listeners. I would suggest rerendering the component after removing it or having both present and show and hiding the correct one based on some conditions.
