### ISSUE TITLE
Updating TextLayer

### ISSUE THREAD

**Issue by sanjaykumar66** [megasanjay/vue3-lottie#65]
How to update TextLayer in JSON. In lottiePlayer package updateDocumentData method will be there for editing text layers like these is there any event for this?

**Comment by megasanjay** [comment]
I can take a look at this and see if I can implement it. I will post updates when its done.

**Comment by sanjaykumar66** [comment]
updateDocumentData method is exported in Lottiplayer Package.
 Add this method it will update the textlayer data.
const updateDocumentData = (index,obj)=>{
      lottieAnimation.renderer.elements[index].updateDocumentData(obj)
    };
